version: '3.3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: 'investment'
      POSTGRES_PASSWORD: 'investor'
      POSTGRES_DB: 'investment'
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
